name: Full Build

on:
  workflow_dispatch:
  workflow_call:

env:
  SOLUTION_FOLDER: "./src/ScottPlot5"

jobs:
  full:
    name: Full Build
    runs-on: windows-latest
    permissions:
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: csharp
          build-mode: manual
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "microsoft"
          java-version: "17"
      - name: Remove Heavy Projects
        working-directory: ${{ env.SOLUTION_FOLDER }}
        run: |
          dotnet sln remove "ScottPlot5 Sandbox\Sandbox.Maui"
          dotnet sln remove "ScottPlot5 Sandbox\Sandbox.WinUI.Desktop"
          dotnet sln remove "ScottPlot5 Sandbox\Sandbox.Blazor.WebAssembly"
      - name: Install Workloads
        working-directory: ${{ env.SOLUTION_FOLDER }}
        run: |
          dotnet workload install maui-android maui-ios maccatalyst wasm-tools
          dotnet workload restore
      - name: Build Solution
        working-directory: ${{ env.SOLUTION_FOLDER }}
        run: |
          dotnet restore
          dotnet build --configuration Release
      - name: Run Tests
        working-directory: ${{ env.SOLUTION_FOLDER }}
        run: dotnet test --configuration Release --no-build --verbosity minimal
      - name: Check for Vulnerable Packages
        working-directory: ${{ env.SOLUTION_FOLDER }}
        run: dotnet list package --vulnerable
      - name: Security Scan
        uses: github/codeql-action/analyze@v3
